project_id = "cpjamwmwzrgqhfnirikz"

[functions.bunny-video]
verify_jwt = false

[functions.sync-enrollment]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-missing-certificate]
verify_jwt = false

[functions.send-certificate]
verify_jwt = false

[functions.download-certificate]
verify_jwt = false

[functions.progress-video-complete]
verify_jwt = false

[functions.check-course-completion]
verify_jwt = false

[functions.send-course-completion]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.upload-certificate-template]
verify_jwt = false

[functions.send-beta-feedback]
verify_jwt = false

[functions.send-refund-notification]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-custom-notification]
verify_jwt = false
