project_id = "cpjamwmwzrgqhfnirikz"

[functions.bunny-video]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-missing-certificate]
verify_jwt = false

[functions.send-certificate]
verify_jwt = false

[functions.download-certificate]
verify_jwt = false
