import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { CheckCircle, XCircle } from "lucide-react";
import { level3ExamQuestions } from "@/data/level3ExamQuestions";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";

interface QuizProps {
  courseType?: 'level2' | 'level3';
}

const Quiz = ({ courseType = 'level3' }: QuizProps) => {
  const { toast } = useToast();
  const [questions] = useState(level3ExamQuestions);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});
  const [showResults, setShowResults] = useState(false);
  const [selectedAnswer, setSelectedAnswer] = useState<string>("");

  const handleAnswerSelect = (value: string) => {
    setSelectedAnswer(value);
  };

  const handleNextQuestion = () => {
    if (selectedAnswer) {
      setSelectedAnswers(prev => ({
        ...prev,
        [currentQuestion]: parseInt(selectedAnswer)
      }));
      
      if (currentQuestion < questions.length - 1) {
        setCurrentQuestion(prev => prev + 1);
        setSelectedAnswer("");
      } else {
        setShowResults(true);
      }
    }
  };

  const handlePreviousQuestion = () => {
    if (currentQuestion > 0) {
      setCurrentQuestion(prev => prev - 1);
      setSelectedAnswer(selectedAnswers[currentQuestion - 1]?.toString() || "");
    }
  };

  const calculateScore = () => {
    let correct = 0;
    Object.entries(selectedAnswers).forEach(([questionIndex, answer]) => {
      if (questions[parseInt(questionIndex)].correctAnswer === answer) {
        correct++;
      }
    });
    return correct;
  };

  const saveCompletion = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return false;

    const score = calculateScore();
    const percentage = Math.round((score / questions.length) * 100);
    const passed = percentage >= 75;

    // Get enrollment data for user's name
    const { data: enrollment } = await supabase
      .from('enrollments')
      .select('first_name, last_name, last_six_digits, identification_type')
      .eq('user_id', user.id)
      .eq('course_type', courseType)
      .single();

    const fullName = enrollment 
      ? `${enrollment.first_name} ${enrollment.last_name}` 
      : 'Student';

    // Save course completion
    const { data: completionData, error: completionError } = await supabase
      .from('course_completions')
      .insert({
        user_id: user.id,
        course_type: courseType,
        score,
        total_questions: questions.length,
        percentage,
        passed
      })
      .select()
      .single();

    if (completionError) {
      console.error('Error saving completion:', completionError);
      toast({
        title: "Error",
        description: "Failed to save your results. Please contact support.",
        variant: "destructive",
      });
      return false;
    }

    let registrationNumber = null;
    let approvalCode = null;
    let approvalExpiresAt = null;

    if (passed && completionData && enrollment) {
      if (courseType === 'level2') {
        // For Level 2: Create certificate
        const { data: certData, error: certError } = await supabase
          .from('certificates')
          .insert({
            user_id: user.id,
            completion_id: completionData.id,
            course_type: courseType,
            student_name: fullName,
            completion_date: new Date().toISOString().split('T')[0],
            last_six_digits: enrollment.last_six_digits,
            identification_type: enrollment.identification_type,
            registration_number: null // Will be generated by database
          })
          .select()
          .single();

        if (!certError && certData) {
          registrationNumber = certData.registration_number;
        }
      } else {
        // For Level 3: Generate approval code instead of certificate
        const expiresAt = new Date();
        expiresAt.setHours(expiresAt.getHours() + 24);

        const { data: approvalData, error: approvalError } = await supabase
          .from('level3_approvals')
          .insert({
            user_id: user.id,
            completion_id: completionData.id,
            approval_code: null, // Will be generated by database function
            expires_at: expiresAt.toISOString()
          })
          .select()
          .single();

        if (!approvalError && approvalData) {
          approvalCode = approvalData.approval_code;
          approvalExpiresAt = new Date(approvalData.expires_at).toLocaleString();
        }
      }
    }

    // Send completion email (for both pass and fail)
    try {
      const { error: emailError } = await supabase.functions.invoke('send-course-completion', {
        body: {
          email: user.email,
          studentName: fullName,
          courseType: courseType,
          score,
          totalQuestions: questions.length,
          percentage,
          passed,
          registrationNumber,
          approvalCode,
          approvalExpiresAt
        }
      });

      if (emailError) {
        console.error('Error sending email:', emailError);
        toast({
          title: "Note",
          description: "Results saved but confirmation email failed to send.",
          variant: "default",
        });
      } else {
        toast({
          title: "Email Sent",
          description: "Check your email for your exam results.",
        });
      }
    } catch (error) {
      console.error('Error sending email:', error);
    }

    // Send admin notification
    try {
      await supabase.functions.invoke('send-admin-notification', {
        body: {
          studentName: fullName,
          studentEmail: user.email,
          courseType: courseType,
          score,
          totalQuestions: questions.length,
          percentage,
          passed,
          registrationNumber,
          approvalCode,
          completedAt: new Date().toISOString()
        }
      });
    } catch (error) {
      console.error('Error sending admin notification:', error);
      // Don't show error to user - admin notifications are internal
    }

    return true;
  };


  const progress = ((currentQuestion + 1) / questions.length) * 100;
  const score = calculateScore();
  const percentage = Math.round((score / questions.length) * 100);

  if (showResults) {
    const passingScore = 75;
    const passed = percentage >= passingScore;
    
    // Save completion when results are shown (only once)
    const hasCompleted = sessionStorage.getItem(`quiz-completed-${courseType}`);
    if (!hasCompleted) {
      saveCompletion();
      sessionStorage.setItem(`quiz-completed-${courseType}`, 'true');
    }
    
    return (
      <div className="max-w-4xl mx-auto space-y-6">
        <Card>
          <CardHeader className="text-center">
            <CardTitle className="text-2xl">Level 3 Security Officer Exam Complete!</CardTitle>
            <CardDescription>Here are your results</CardDescription>
          </CardHeader>
          <CardContent className="text-center space-y-6">
            <div className="text-6xl">
              {passed ? "🎉" : "📚"}
            </div>
            <div>
              <div className="text-4xl font-bold text-primary mb-2">
                {score}/{questions.length}
              </div>
              <div className="text-xl text-muted-foreground">
                {percentage}% Score
              </div>
            </div>
            <div className={`text-lg font-semibold ${passed ? 'text-green-600' : 'text-orange-600'}`}>
              {passed 
                ? 'Congratulations! You passed the Level 3 Security Officer Certification Exam!' 
                : `You need ${passingScore}% to pass. Keep studying and try again!`}
            </div>
            {passed && courseType === 'level2' && (
              <div className="p-4 bg-green-50 dark:bg-green-950/20 rounded-lg border-2 border-green-500">
                <p className="text-sm font-semibold text-green-900 dark:text-green-100 mb-2">
                  ✓ Certificate Available
                </p>
                <p className="text-sm text-green-800 dark:text-green-200">
                  Your Level 2 Security Officer certificate is now available in your user profile. 
                  You can download it at any time by visiting your profile page.
                </p>
              </div>
            )}
            {passed && courseType === 'level3' && (
              <div className="p-4 bg-blue-50 dark:bg-blue-950/20 rounded-lg border-2 border-blue-500">
                <p className="text-sm font-semibold text-blue-900 dark:text-blue-100 mb-2">
                  ⚠️ IMPORTANT: Level 3 Part 2 In-Person Training Required
                </p>
                <p className="text-sm text-blue-800 dark:text-blue-200">
                  You have completed Part 1 (Online). To receive your Armed Security Officer certificate, 
                  you MUST complete Part 2 in-person training. Check your email for your approval code 
                  to schedule your in-person session. The approval code expires in 24 hours.
                </p>
              </div>
            )}
            {!passed && (
              <div className="p-4 bg-orange-50 dark:bg-orange-950/20 rounded-lg">
                <p className="text-sm text-orange-800 dark:text-orange-200">
                  Review the course materials and retake the exam when you're ready. You'll need a score of 75% or higher to pass.
                </p>
              </div>
            )}
            
            <div className="space-y-4">
              <h3 className="font-semibold text-lg">Your Answers:</h3>
              {questions.map((question, index) => {
                const userAnswer = selectedAnswers[index];
                const isCorrect = userAnswer === question.correctAnswer;
                
                return (
                  <div 
                    key={index} 
                    className={`p-4 rounded-lg border-2 ${
                      isCorrect 
                        ? 'bg-green-50 dark:bg-green-950/20 border-green-500' 
                        : 'bg-red-50 dark:bg-red-950/20 border-red-500'
                    }`}
                  >
                    <div className="flex items-start gap-2 mb-2">
                      {isCorrect ? (
                        <CheckCircle className="h-5 w-5 text-green-600 flex-shrink-0 mt-1" />
                      ) : (
                        <XCircle className="h-5 w-5 text-red-600 flex-shrink-0 mt-1" />
                      )}
                      <div className="flex-1">
                        <p className="font-medium mb-2">{question.question}</p>
                        <div className="space-y-1 text-sm">
                          <p className={userAnswer === question.correctAnswer ? 'text-green-700 dark:text-green-300' : 'text-red-700 dark:text-red-300'}>
                            Your answer: {question.options[userAnswer]}
                          </p>
                          {!isCorrect && (
                            <p className="text-green-700 dark:text-green-300">
                              Correct answer: {question.options[question.correctAnswer]}
                            </p>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
            
            <div className="flex gap-4 justify-center">
              <Button 
                onClick={() => {
                  setShowResults(false);
                  setCurrentQuestion(0);
                  setSelectedAnswers({});
                  setSelectedAnswer("");
                  sessionStorage.removeItem(`quiz-completed-${courseType}`);
                }}
              >
                Retake Exam
              </Button>
              <Button variant="outline" onClick={() => window.location.href = '/courses'}>
                Back to Courses
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  const question = questions[currentQuestion];
  
  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <Card>
        <CardHeader>
          <div className="flex justify-between items-center mb-2">
            <CardTitle>Level 3 Security Officer Exam</CardTitle>
            <span className="text-sm text-muted-foreground">
              Question {currentQuestion + 1} of {questions.length}
            </span>
          </div>
          <Progress value={progress} className="h-2" />
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">{question.question}</h3>
            <RadioGroup value={selectedAnswer} onValueChange={handleAnswerSelect}>
              {question.options.map((option, index) => (
                <div key={index} className="flex items-center space-x-2 p-3 rounded-lg hover:bg-accent">
                  <RadioGroupItem value={index.toString()} id={`option-${index}`} />
                  <Label htmlFor={`option-${index}`} className="flex-1 cursor-pointer">
                    {option}
                  </Label>
                </div>
              ))}
            </RadioGroup>
          </div>

          <div className="flex justify-between pt-4">
            <Button
              variant="outline"
              onClick={handlePreviousQuestion}
              disabled={currentQuestion === 0}
            >
              Previous
            </Button>
            <Button
              onClick={handleNextQuestion}
              disabled={!selectedAnswer}
            >
              {currentQuestion === questions.length - 1 ? 'Finish' : 'Next'}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default Quiz;
