INSERT INTO beta_feedback (
  name_role,
  experience_level,
  device_browser,
  testing_time,
  login_clarity,
  layout_rating,
  materials_location,
  visual_design,
  branding,
  video_playback,
  ai_assistant,
  materials_usefulness,
  content_engagement,
  technical_issues,
  test_location,
  test_interface,
  score_comm,
  certificate_delivery,
  certificate_download,
  accessibility_issues,
  mobile_adaptation
) VALUES (
  'Test User - QA Tester',
  'Intermediate - used several online training platforms',
  'Chrome on Windows 11',
  'About 45 minutes',
  'Very clear and intuitive, found the course immediately',
  '4/5 - Clean layout, easy to navigate',
  'Yes, found everything easily',
  'Professional look, good color scheme',
  'Yes, fits the security training industry well',
  'Videos loaded quickly and played smoothly',
  'Helpful for answering questions about the material',
  'Very useful, comprehensive coverage',
  'Engaging content, good pacing',
  'No major issues encountered',
  'Easy to find after completing the course',
  'Straightforward multiple choice format',
  'Yes, clearly showed pass threshold and final score',
  'Received certificate email promptly after passing',
  'Download worked smoothly',
  'No accessibility issues noticed',
  'Site adapted well on tablet'
);