export interface ExamQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
}

export const level3ExamQuestions: ExamQuestion[] = [
  {
    id: 1,
    question: "Do security officers have the same authority to arrest as peace officers?",
    options: [
      "Yes; their authority to arrest is the same.",
      "No; they have no authority to arrest.",
      "No; they have the same authority to arrest as a citizen.",
      "No; they may only arrest someone with a weapon."
    ],
    correctAnswer: 2 // C
  },
  {
    id: 2,
    question: "PC 37.11 and 37.12 are associated with ___________.",
    options: [
      "arrest authority",
      "impersonating a public servant",
      "right to carry",
      "kidnapping"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 3,
    question: "__________ has the right to prevent theft by seizing of any personal property stolen and bringing it, and the person suspected of stealing, before a magistrate or peace officer.",
    options: [
      "A security officer",
      "A peace officer",
      "Anyone",
      "A citizen"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 4,
    question: "A __________ is an instrument that is specially designed, made, or adapted for the purpose of inflicting serious bodily injury or death by striking a person with the instrument.",
    options: [
      "club",
      "firearm",
      "fist",
      "bullet"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 5,
    question: "OC spray falls under the category of what type of weapon?",
    options: [
      "Stun gun",
      "Chemical dispensing device",
      "Club",
      "Shotgun"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 6,
    question: "A person can use a License to Carry (LTC) issued by the Texas Department of Public Safety to carry.",
    options: [
      "True; there is not a law that restricts a security officer's use of their LTC.",
      "False; a security officer must be commissioned and receive training to carry a firearm.",
      "True; the law explicitly allows a security officer's use of their LTC",
      "False; a security officer may never carry a firearm"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 7,
    question: "A person commits an aggravated assault if during the assault they __________.",
    options: [
      "cause serious bodily injury to another person.",
      "commit the assault in a fit of rage.",
      "use or exhibit a deadly weapon.",
      "Both A & C"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 8,
    question: "__________ means any device designed, made, or adapted to expel a projectile through a barrel using the energy generated by an explosion or burning substance.",
    options: [
      "Firearm",
      "Explosive weapon",
      "Handgun",
      "Hoax bomb"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 9,
    question: "Code of Criminal Procedure Art. 14.01 pertains to __________.",
    options: [
      "Offenses committed within the presence or view of the officer",
      "Probable cause detected by the officer",
      "Offenses committed by the officer",
      "Offenses detected by a third party"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 10,
    question: "A __________ radio is a device that can both transmit and receive.",
    options: [
      "binary",
      "CB",
      "two-way",
      "ham"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 11,
    question: "The main responsibilities of a security officer are to __________ & __________.",
    options: [
      "watch; listen",
      "read; write",
      "protect; serve",
      "observe; report"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 12,
    question: "In order to write a detailed, professional report, you must have __________.",
    options: [
      "field notes",
      "good memory",
      "typing skills",
      "ideal conditions"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 13,
    question: "Developing __________ will assist with recording notes quickly.",
    options: [
      "good handwriting",
      "consistent shorthand",
      "writing styles",
      "photographic memory"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 14,
    question: "Reports can be written in __________ format.",
    options: [
      "first person",
      "second person",
      "third person",
      "Both A & C"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 15,
    question: "Using __________ creates clear, strong sentences and emphasizes who is performing the action.",
    options: [
      "passive voice",
      "active verbs",
      "active voice",
      "passive verbs"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 16,
    question: "You should cover the 5 W's + 1 H in your report. Those include __________, When, __________, Who, Where, and How.",
    options: [
      "Whether; Whom",
      "Weather; Whose",
      "Why; What",
      "Wherefore; Which"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 17,
    question: "Ensure your report is written in an objective manner and free from __________.",
    options: [
      "bias",
      "opinions",
      "fabrications",
      "All of the above"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 18,
    question: "When writing a report, you should start __________.",
    options: [
      "with key details",
      "at the beginning",
      "with the results of the situation",
      "with the victim's story"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 19,
    question: "A security guard must do what with evidence?",
    options: [
      "Observe",
      "Protect",
      "Collect",
      "Hide"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 20,
    question: "What should be used to prevent the removal of evidence?",
    options: [
      "Physical barriers",
      "Verbal threats",
      "Use of force",
      "Hiding it"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 21,
    question: "Documenting the time and location of the removal of evidence is known as maintaining __________.",
    options: [
      "daily reports",
      "field notes",
      "evidence articles",
      "chain of custody"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 22,
    question: "When possible, maintain an outer perimeter around a crime scene of at least _________.",
    options: [
      "100 ft",
      "75 ft",
      "50 ft",
      "25 ft"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 23,
    question: "A security officer should maintain a presence at a crime scene until relieved by management or __________.",
    options: [
      "excused by law enforcement",
      "the end of their shift",
      "the close of business",
      "a barrier is set up"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 24,
    question: "Follow __________ when providing information or interviews to media personnel.",
    options: [
      "your instincts",
      "company policy",
      "the script",
      "the law"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 25,
    question: "A security officer may not conduct an investigation other than one __________.",
    options: [
      "connected to an assault on the property they've been hired to protect",
      "connected to a kidnapping on the property they've been hired to protect",
      "connected to loss or theft of property they've been hired to protect",
      "connected to a firearm found on the property they've been hired to protect"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 26,
    question: "__________ refers to objects or structures that provide persons protection from harm.",
    options: [
      "Cover",
      "Concealment",
      "Armor",
      "Kevlar"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 27,
    question: "__________ refers to objects or structures that obscure persons from being seen.",
    options: [
      "Cover",
      "Concealment",
      "Armor",
      "Kevlar"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 28,
    question: "Situational awareness refers to security officers being aware of their __________.",
    options: [
      "location",
      "conditions",
      "circumstances",
      "All of the above"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 29,
    question: "__________ occurs when someone is standing in an exposed area, such as a doorway when moving from a well-lit area to an area with less light.",
    options: [
      "Shadowing",
      "Silhouetting",
      "Backlighting",
      "Both B & C"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 30,
    question: "Security officers should know the __________ and __________ of crime in the area in which they operate.",
    options: [
      "place; size",
      "type; volume",
      "gangs; leaders",
      "location; danger"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 31,
    question: "Reasonable or necessary force is the __________.",
    options: [
      "maximum amount of force a person can use",
      "minimum amount of force a person can use",
      "amount of legal force that a person can use to achieve a lawful objective",
      "amount of force that doesn't result in death"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 32,
    question: "Deadly force is force that is intended to, or known by the actor to cause, death or __________.",
    options: [
      "fear of death",
      "serious bodily injury",
      "serious pain",
      "All of the above"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 33,
    question: "Which amendments to the United States Constitution pertain to the use of force?",
    options: [
      "4th & 14th",
      "2nd & 19th",
      "5th & 7th",
      "The Constitution doesn't pertain to the use of force."
    ],
    correctAnswer: 0 // A
  },
  {
    id: 34,
    question: "The use of force is not justified for __________.",
    options: [
      "self-defense",
      "defense of a third person",
      "verbal provocation",
      "defense of property"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 35,
    question: "A security officer's authority to arrest can be applied to a person __________.",
    options: [
      "committing a felony",
      "committing hate speech",
      "committing a breach of the peace",
      "Both A & C"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 36,
    question: "What is the proper type of force to use in response to Non-Threatening Resistance?",
    options: [
      "Pressure points",
      "All tools",
      "Intermediate weapons",
      "Verbal commands"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 37,
    question: "The five options of the use of force model are: • __________ • __________ • Empty Hand Control • Personal Weapons/Non-Lethal Weapons • __________",
    options: [
      "Presence; Verbal commands; Deadly force",
      "Perception; Demands; Deadly force",
      "Observation; Demonstration; Batons",
      "Passive; Active; Demonstrable"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 38,
    question: "Most situations a security officer encounters will end with __________.",
    options: [
      "their presence",
      "verbal commands",
      "soft controls",
      "deadly force"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 39,
    question: "__________ is/are defined by a level of force that is unlikely to cause damage to soft tissues.",
    options: [
      "Verbal commands",
      "Professional appearances",
      "Empty hand control",
      "Arrest authorities"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 40,
    question: "__________ can be viewed as deadly force if used against the head, neck, groin, kneecaps, or spine.",
    options: [
      "Pressure points",
      "Soft controls",
      "Basic strikes",
      "Intermediate weapons"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 41,
    question: "Deadly force is a(n) __________.",
    options: [
      "natural instinct",
      "last resort",
      "illegal action",
      "standard response"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 42,
    question: "__________ denotes the extent to which a security company or officer is perceived as morally just, honest, and worthy of trust and confidence.",
    options: [
      "Legitimacy",
      "Transparency",
      "Respect",
      "Fairness"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 43,
    question: "What does CDM stand for?",
    options: [
      "Correctly Determining Motives",
      "Currently Doing Mayhem",
      "Critical Decision-Making Model",
      "Crucial Defensive Movements"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 44,
    question: "What is the goal of using the CDM?",
    options: [
      "To resolve critical incidents as quickly as possible",
      "To more effectively and safely resolve critical incidents",
      "To deter critical incidents from happening",
      "To predict future critical incidents"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 45,
    question: "The four key principles of the CDM are as follows: • __________ • Values of the company • Proportionality • __________",
    options: [
      "Ethics; Protection of property",
      "Knowing your limits; Protection of property",
      "Knowing your limits; Sanctity of human life",
      "Ethics; Sanctity of human life"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 46,
    question: "There are __________ steps in the CDM.",
    options: [
      "five",
      "eight",
      "ten",
      "Undefined; it varies based on the situation"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 47,
    question: "The first step of the CDM is __________.",
    options: [
      "Collect Information",
      "Asses Situation, Threat, and Risks",
      "Identify Options and Determine the Best Course of Action",
      "Act, Review, and Reassess"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 48,
    question: "If the incident is not resolved after the final step of the CDM, what should you do?",
    options: [
      "Call law enforcement",
      "Escalate the type of force used",
      "Start the process again",
      "Choose a new model to try"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 49,
    question: "The distance that provides you enough time to react to defend yourself is called __________.",
    options: [
      "Reactionary gap",
      "Minimum distance",
      "Reaction time",
      "Combat ready"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 50,
    question: "What does ABC in the context of defensive tactics stand for?",
    options: [
      "Action; Batons; Conflict",
      "Awareness; Barrier; Counter",
      "Aggressive; Battle; Crucial",
      "Active; Barrier; Conflict"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 51,
    question: "The __________ stance allows you to move to a combat-ready stance quickly.",
    options: [
      "reactionary",
      "active",
      "preparation",
      "interview"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 52,
    question: "__________ are restraint devices made of two halves, each with a movable single bar and a static bar held together by a locking device.",
    options: [
      "Ropes",
      "Handcuffs",
      "Chains",
      "Caution Tape"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 53,
    question: "When using handcuffs, a __________ prevents the rachet from working by locking the single bar in place to prevent it from over tightening on the wrist.",
    options: [
      "double-lock",
      "safety pin",
      "bar stop",
      "blocker"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 54,
    question: "When applying handcuffs, you should hold them with your __________ hand.",
    options: [
      "right",
      "left",
      "strong",
      "support"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 55,
    question: "How should you grip a baton?",
    options: [
      "Slightly above the end securely between the two middle fingers and thumb",
      "Near the top of the handle in a tight fist",
      "Slightly above the end in a tight fist",
      "Near the top of the handle securely between the two middle fingers and thumb"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 56,
    question: "What is the reactionary gap with baton?",
    options: [
      "The time is takes to react to stimulus.",
      "The gap in time between being struck and feeling pain.",
      "The distance between the security officer and the suspect.",
      "None of the above."
    ],
    correctAnswer: 2 // C
  },
  {
    id: 57,
    question: "What stance is assumed when a threat is perceived that will require the baton to be used?",
    options: [
      "Interview",
      "Defensive",
      "Reactionary",
      "Ready"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 58,
    question: "The two basic revolver actions are __________ and __________.",
    options: [
      "double action; single action",
      "double shot; single action",
      "double action; single shot",
      "double shot; single shot"
    ],
    correctAnswer: 0 // A
  },
  {
    id: 59,
    question: "Before you clean a firearm, you must __________.",
    options: [
      "disengage the safety",
      "check to ensure it is empty and unloaded",
      "take off the grips",
      "fire the round from the chamber"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 60,
    question: "Which of the following is not a rule for the safe handling of a weapon while at home:",
    options: [
      "Never assume a small child cannot fire a firearm.",
      "Establish strict rules about handling of firearms.",
      "Never put your firearm in a gun safe so that it can be easily accessible.",
      "Never use a firearm when intoxicated."
    ],
    correctAnswer: 2 // C
  },
  {
    id: 61,
    question: "Proper trigger control means you should __________ the trigger.",
    options: [
      "jerk",
      "pull",
      "yank",
      "squeeze"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 62,
    question: "Revolvers can be reloaded quickly with a __________.",
    options: [
      "magazine",
      "speed loader",
      "multi-loader",
      "all of the above"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 63,
    question: "Which of the following is not a part of proper security officer positioning while in an interview stance?",
    options: [
      "Stand at approximately a 45 degree angle, slightly off center of the person to whom you are speaking.",
      "Keep your hands in front of you and above the waistline; do not interlace your fingers.",
      "Staying tense",
      "Set your strong foot back slightly to protect your firearm."
    ],
    correctAnswer: 2 // C
  },
  {
    id: 64,
    question: "Another word for lethal force is __________.",
    options: [
      "intermediate weapons",
      "involving police",
      "deadly force",
      "none of these"
    ],
    correctAnswer: 2 // C
  },
  {
    id: 65,
    question: "It is important to try and gain ________________ to resolve situations without using force.",
    options: [
      "physical submission",
      "complete information",
      "good observations",
      "voluntary compliance"
    ],
    correctAnswer: 3 // D
  },
  {
    id: 66,
    question: "Section 9 of the State of Texas Penal Code focuses on ___________.",
    options: [
      "uniforms",
      "use of force",
      "carrying firearms",
      "vehicles"
    ],
    correctAnswer: 1 // B
  },
  {
    id: 67,
    question: "It is important to remain __________ when talking on the radio.",
    options: [
      "stern",
      "authoritative",
      "loud",
      "calm"
    ],
    correctAnswer: 3 // D
  }
];
