export interface ExamQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
}

export const level3ExamQuestions: ExamQuestion[] = [
  {
    id: 1,
    question: "A security officer has the powers and authority of a:",
    options: ["Company president", "Peace officer", "Private citizen"],
    correctAnswer: 2
  },
  {
    id: 2,
    question: "A person can use a License to Carry (LTC) issued by the Texas Department of Public Safety to carry a firearm while working as a security officer or personal protection officer.",
    options: ["False", "True"],
    correctAnswer: 0
  },
  {
    id: 3,
    question: "The use of force is justified in response to verbal provocation alone.",
    options: ["False", "True"],
    correctAnswer: 0
  },
  {
    id: 4,
    question: "What is the primary difference between robbery and theft?",
    options: ["The value of the item taken", "The fact the property was taken from a residence rather than a business", "The type of entry used", "The use of force or attempted use of force"],
    correctAnswer: 3
  },
  {
    id: 5,
    question: "What does the Code of Criminal Procedure Art. 14.01 deal with?",
    options: ["Offenses committed within the presence or view of the officer", "Probable cause detected by the officer", "Offenses pointed out by the officer", "Offenses pointed out by the third party"],
    correctAnswer: 0
  },
  {
    id: 6,
    question: "Means any device designed, made or adapted to expel a projectile through a barrel using the energy generated by an explosion or burning substance.",
    options: ["Machine gun", "Explosives weapon", "Firearm", "Handgun"],
    correctAnswer: 2
  },
  {
    id: 7,
    question: "A person who intentionally or knowingly restrains another person may be found guilty of",
    options: ["Kidnapping", "Unlawful restraint", "False arrest", "Violating a prisoner's rights"],
    correctAnswer: 1
  },
  {
    id: 8,
    question: "Which of the following force options is the lowest level of control available to you to gain voluntary compliance?",
    options: ["Weaponless strategies / empty hand control", "Professional presence", "Intermediate weapons", "Deadly force"],
    correctAnswer: 1
  },
  {
    id: 9,
    question: "Persons handling firearms should always treat every gun as if it were loaded.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 10,
    question: "Distance is",
    options: ["True", "False", "An option", "Not necessary"],
    correctAnswer: 0
  },
  {
    id: 11,
    question: "Once the weapon has been checked and found to be unloaded, it is not necessary to check it again.",
    options: ["True", "False"],
    correctAnswer: 1
  },
  {
    id: 12,
    question: "Warning shots should not be fired because",
    options: ["It might scare innocent bystanders", "It is a waste of ammunition", "You do not know where the bullet will strike"],
    correctAnswer: 2
  },
  {
    id: 13,
    question: "The two basic revolver actions are:",
    options: ["Double action and single action", "Double action and single shot", "Single action and double action only"],
    correctAnswer: 0
  },
  {
    id: 14,
    question: "The device which holds the cartridges for a semi-auto pistol is called a:",
    options: ["Clip", "Cartridge retaining device", "Magazine", "Speed loaders"],
    correctAnswer: 2
  },
  {
    id: 15,
    question: "Before you clean a firearm, you must:",
    options: ["Engage the safety", "Check to insure it is empty and unloaded", "Take off the grips", "Fire the round in the chamber"],
    correctAnswer: 1
  },
  {
    id: 16,
    question: "Tactical shooting is normally done with both eyes:",
    options: ["Closed", "Open", "One eye closed"],
    correctAnswer: 1
  },
  {
    id: 17,
    question: "Proper trigger control means you should:",
    options: ["Jerk the trigger", "Stroke the trigger", "Press the trigger slowly to the rear"],
    correctAnswer: 2
  },
  {
    id: 18,
    question: "Revolvers can be reloaded quickly with:",
    options: ["Speed loaders", "Multi-loaders", "Magazines"],
    correctAnswer: 0
  },
  {
    id: 19,
    question: "The Type One semi-auto stoppage drill is Tap, Rack and Assess.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 20,
    question: "The most common shotgun gauge used by security and law enforcement is:",
    options: ["410", "16", "10", "12"],
    correctAnswer: 3
  },
  {
    id: 21,
    question: "The maximum range for the shotgun is:",
    options: ["1 foot", "200 yards", "500 yards", "1,000 yards"],
    correctAnswer: 2
  },
  {
    id: 22,
    question: "The prevention of removal of evidence can be accomplished by the use of:",
    options: ["Rope", "Barricades", "Additional personnel", "All of the above"],
    correctAnswer: 3
  },
  {
    id: 23,
    question: "Which of these makes good cover?",
    options: ["Bushes", "Sheetrock", "Hollow core door", "Concrete column"],
    correctAnswer: 3
  },
  {
    id: 24,
    question: "Three positions involving handcuffing are:",
    options: ["Standing, Kneeling, Prone", "Standing, Sitting, Prone", "Kneeling, Sitting, Standing", "Prone, Supine, Standing"],
    correctAnswer: 0
  },
  {
    id: 25,
    question: "A tie, belt or shoelaces make a good supplement to handcuffs.",
    options: ["True", "False"],
    correctAnswer: 1
  },
  {
    id: 26,
    question: "Handcuffs are a restraining device.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 27,
    question: "After the application of handcuffs, the officer should:",
    options: ["Double lock the handcuff", "Give the suspect a hug", "Slap the suspect", "Kidney punch the suspect"],
    correctAnswer: 0
  },
  {
    id: 28,
    question: "It is important in awareness situation to not allow yourself to be back-lighted.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 29,
    question: "Back-lighting is done by someone or something shining a light behind you, thus creating a silhouette making it easy for the suspect to see you.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 30,
    question: "If a security officer purports themselves to be a peace officer, he / she can be charged with:",
    options: ["Highway mopery", "Impersonating a peace officer", "Playing cops and robbers", "Carrying an unlawful weapon"],
    correctAnswer: 1
  },
  {
    id: 31,
    question: "An arrest warrant or capias issued under the Code of Criminal Procedure (17.19 Surety may be executed by a peace officer, a security officer, or a private investigator licensed in this state.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 32,
    question: "A security officer does not need to be trained in the use of chemical dispensing agents in order to legally carry them.",
    options: ["True", "False"],
    correctAnswer: 1
  },
  {
    id: 33,
    question: "Uncle Earl intentionally and knowingly damages the tangible property of his neighbor Ricky Bobby, without Ricky Bobby's permission. Uncle Earl can be charged with:",
    options: ["Homicide", "Robbery", "Criminal Mischief", "Burglary"],
    correctAnswer: 2
  },
  {
    id: 34,
    question: "You are working at a Hell's Angels bar. You hear someone using profane language. No one seems to be offended and actually cheers them on; the person using profane language can be charged with:",
    options: ["Disorderly conduct", "Criminal mischief", "Criminal trespass", "No charge because Jim Bob has his First Amendment rights"],
    correctAnswer: 3
  },
  {
    id: 35,
    question: "You are at your local church working security when Jim Bob walks in and begins using vulgar, profane language. The very words he uses causes the minister to stop and the congregation asks for his removal as they are offended by his language. Jim Bob could be charged with:",
    options: ["Disorderly conduct", "Criminal mischief", "Criminal trespass", "No charge because Jim Bob has his First Amendment rights"],
    correctAnswer: 0
  },
  {
    id: 36,
    question: "The vile and despicable villain Janie is without a man. Janie decides to get her one by any means so she intentionally abducts innocent Ron, who is 19 years old. Janie can be charged with:",
    options: ["Kidnapping", "Aggravated kidnapping", "Criminal mischief", "Disorderly conduct"],
    correctAnswer: 0
  },
  {
    id: 37,
    question: "Satan's sister Lucy intentionally and knowingly abducts Jimmy Joe and calls his family and states: \"I want five million dollars or Jimmy Joe gets it.\" Lucy can be charged with:",
    options: ["Kidnapping", "Aggravated kidnapping", "Criminal mischief", "Being ornery"],
    correctAnswer: 1
  },
  {
    id: 38,
    question: "Criminal Code of Procedure Art. 16.06 states, you must take the suspect before a magistrate without delay.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 39,
    question: "Field notes are circumstances which are recorded while fresh in the officer's mind and used to prepare the report.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 40,
    question: "Two types of reports used in the security industry are:",
    options: ["Coded and long", "Expanded and narrative", "Pre-printed and summary", "None of the above"],
    correctAnswer: 1
  },
  {
    id: 41,
    question: "The reporting officer should include his opinion in the report.",
    options: ["True", "False"],
    correctAnswer: 1
  },
  {
    id: 42,
    question: "Which of the below is important information when writing your report?",
    options: ["Name", "Address", "Phone number", "Driver's license number", "They are all important"],
    correctAnswer: 4
  },
  {
    id: 43,
    question: "The pressure point located near the upper lip and nose is called the:",
    options: ["Mandibular angle", "Radial", "Infra orbital", "Brachial plexus"],
    correctAnswer: 2
  },
  {
    id: 44,
    question: "Texas Penal Code 9.31 allows for:",
    options: ["Preventing the consequences of theft", "Protection of property", "Aiding in suicide", "Self-defense"],
    correctAnswer: 3
  },
  {
    id: 45,
    question: "To protect and secure a crime scene, the security officer should:",
    options: ["Call the media so he can be on television", "Make sure people do not enter or disturb the crime scene", "Dust for fingerprints", "Collect and tag evidence"],
    correctAnswer: 1
  },
  {
    id: 46,
    question: "Article 17.19 of the Texas Code of Criminal Procedure allows a security officer to:",
    options: ["Execute a warrant issued to a surety", "Prevent the consequences of theft", "Detain the suspect", "Search a suspect"],
    correctAnswer: 0
  },
  {
    id: 47,
    question: "Texas Penal Code 30.05 covers the offense of:",
    options: ["Criminal trespass", "Felony theft", "Capital murder", "Assault"],
    correctAnswer: 0
  },
  {
    id: 48,
    question: "Deadly force may be used to protect property, in the event of:",
    options: ["Arson", "Theft during the night time", "Burglary", "Criminal mischief during the night time", "All of the above"],
    correctAnswer: 4
  },
  {
    id: 49,
    question: "John, in his infinite wisdom, decides to intentionally and knowingly enter his neighbor's house without his neighbor's permission with the thought of taking something that does not belong to him. While Leah, John's neighbor, is gone for the day, John enters her home and takes her big screen television. John can be charged with:",
    options: ["Burglary", "Robbery", "Criminal Mischief", "Aggravated stupidity"],
    correctAnswer: 0
  },
  {
    id: 50,
    question: "Billy Bob is smarter than everyone else in the world and knows the law. Billy Bob fashions a make-shift hook. Billy Bob reaches into Kevin's home with the hook and takes a painting from Kevin's home. Billy Bob can be charged with:",
    options: ["Burglary", "Robbery", "Criminal Mischief", "No charge because he is just misunderstood"],
    correctAnswer: 0
  },
  {
    id: 51,
    question: "Joe S. Ragman is walking down a country road. He notices a nice lake that has lots of fish in it. The lake is on private property and has a barbed wire fence and \"No Trespassing\" signs. Joe can be charged with:",
    options: ["No charge", "Criminal trespass", "Burglary", "Making Sunnie really mad"],
    correctAnswer: 1
  },
  {
    id: 52,
    question: "We can increase or decrease the chances of being chosen as the victim of a violent criminal attack by the way we walk, move and carry ourselves.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 53,
    question: "Determining what level of force we might use in a given situation is a matter that includes an assessment of the \"Totality of the",
    options: ["Determinants", "Basics", "Circumstances", "Components"],
    correctAnswer: 2
  },
  {
    id: 54,
    question: "The use of force commands with strikes is essential.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 55,
    question: "The totality of circumstances might include:",
    options: ["Multiple subjects", "Proximity of weapon to the suspect", "Size of the suspect vs. the size of the officer", "Non-verbal cues from the suspect", "All of the above"],
    correctAnswer: 4
  },
  {
    id: 56,
    question: "Force that can cause serious bodily injury and / or death is considered deadly force.",
    options: ["Injury", "Serious bodily injury", "Headache", "Rack"],
    correctAnswer: 1
  },
  {
    id: 57,
    question: "Type Two stoppage drill requires one to Rip and Reload.",
    options: ["Rip", "Remember", "Rock", "Roll"],
    correctAnswer: 2
  },
  {
    id: 58,
    question: "Who, What, When, Where, Why and How are the basics of any investigation.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 59,
    question: "When looking through the rear sight, if the front sight is higher than the rear sight, the bullet will strike the target.",
    options: ["In the center", "Higher than center", "Lower than center"],
    correctAnswer: 1
  },
  {
    id: 60,
    question: "When reloading a revolver in a tactical situation, you should:",
    options: ["Catch the empty cartridges in your hand", "Let the empties fall to the ground", "Save the empty cartridges for later reloading"],
    correctAnswer: 1
  },
  {
    id: 61,
    question: "When taking field notes, you should remember the four B's: Be concise, Be accurate, Be",
    options: ["Specific", "Long", "Good", "On time", "Have"],
    correctAnswer: 0
  },
  {
    id: 62,
    question: "Narrative reports are a summary of the incident.",
    options: ["Long", "Short", "Immediate", "Necessary"],
    correctAnswer: 1
  },
  {
    id: 63,
    question: "Reports should be written in language.",
    options: ["Chinese", "King's English", "Everyday", "One"],
    correctAnswer: 1
  },
  {
    id: 64,
    question: "When dealing with evidence, you should?",
    options: ["Pick it up", "Taste it", "Kick it around", "Log it in your report, but do not pick it up"],
    correctAnswer: 3
  },
  {
    id: 65,
    question: "When standing in a fighting stance, you should stand with your feet in a:",
    options: ["Split position", "Together position", "Slightly wider than shoulder position", "Tip toe position"],
    correctAnswer: 2
  },
  {
    id: 66,
    question: "The Common Peroneal Strike is a strike to the:",
    options: ["Side of the leg", "Head", "Arm", "Shin"],
    correctAnswer: 0
  },
  {
    id: 67,
    question: "A brachial plexus strike can render the assailant",
    options: ["Broke", "Unconscious", "Super human strength", "Jedi-like quickness"],
    correctAnswer: 1
  },
  {
    id: 68,
    question: "You are making rounds at your post at an apartment complex when Mary Jane runs up to you and tells you the man you just saw leave the complex stole her radio. You should:",
    options: ["Get in your car and chase him down", "Nothing as it was not your radio", "Obtain as much information from Mary as you can", "Both c and d"],
    correctAnswer: 3
  },
  {
    id: 69,
    question: "Johnny is walking down the road and sees a nice pond he knows is stocked with fish. Johnny sees a barbed wire fence which contains the cattle of the owner. However, Johnny doesn't see any \"No Trespassing\" signs. Johnny decides to jump the fence and go fishing. The owner, Homer, sees Johnny and tells him to leave the property. Johnny refuses. Johnny can be charged with:",
    options: ["Criminal trespass", "Fishing without a permit", "Aggravating the cows", "Highway mopery"],
    correctAnswer: 0
  },
  {
    id: 70,
    question: "You are at a convenience store in your marked patrol vehicle when a concerned citizen reports what they believe are drag racers getting ready to race on the city street nearby. You might do all of the following except:",
    options: ["Activate your emergency equipment and intervene to arrest the spectators and competitors", "Notify law enforcement of the situation so that they may respond", "Encourage the concerned citizen to contact the police", "Nothing as the infraction is not a felony or breach of the peace"],
    correctAnswer: 0
  },
  {
    id: 71,
    question: "The radial, median and ulna nerves are found in the:",
    options: ["Arm", "Leg", "Back", "What's an ulna"],
    correctAnswer: 0
  },
  {
    id: 72,
    question: "If you qualify with a revolver handgun, you may also carry a semi-automatic pistol.",
    options: ["True", "False"],
    correctAnswer: 1
  },
  {
    id: 73,
    question: "The best way to defuse a situation before it escalates is to use:",
    options: ["Defense tactics", "Communication Skills", "Deadly force", "A hug"],
    correctAnswer: 1
  },
  {
    id: 74,
    question: "Essential elements of a report include",
    options: ["Who", "What", "Where", "When", "All of the above are elements of a good report"],
    correctAnswer: 4
  },
  {
    id: 75,
    question: "Force Options include:",
    options: ["Professional Presence", "Verbal Commands", "Empty Hand Controls", "Intermediate Weapons", "All of the above are Force Options that may be utilized in certain situations"],
    correctAnswer: 4
  },
  {
    id: 76,
    question: "The Dynamic Resistance Response Model identifies 4 levels of suspect resistance. Which of the following best identifies Non-Threatening Resistance?",
    options: ["The suspect isn't following your commands but is not doing anything that causes you to feel physically threatened", "The suspect is compliant", "The suspect attacks the security officer with a knife", "The suspect clenches his fists and tries to move toward the security officer"],
    correctAnswer: 0
  },
  {
    id: 77,
    question: "Article 14.03 Code of Criminal Procedure relates to arrests without warrant for which of the following?",
    options: ["Offense within the view of a magistrate", "An offense committed in his presence or within his view", "Felony or breach of peace committed in his presence", "Peace officer's reasonable suspicion"],
    correctAnswer: 2
  },
  {
    id: 78,
    question: "The suspect's level of resistance determines the level of force (response) by security officers.",
    options: ["Supervisor's", "Owner's", "Suspect's", "Victim's"],
    correctAnswer: 2
  },
  {
    id: 79,
    question: "Deadly force is considered to be the last resort in response to critical situations.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 80,
    question: "The SARA acronym stands for:",
    options: ["Scan, analyze, respond, assess", "Seek, ask, rebut, astound", "Ask, tell, make", "Stop all reasonable allowances"],
    correctAnswer: 0
  },
  {
    id: 81,
    question: "Respect, Legitimacy, Transparency, and Fairness are all important considerations when security officers respond to a situation.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 82,
    question: "What skill helps a security officer to be a good problem solver?",
    options: ["Loud voice", "Size", "Caliber of weapon carried", "Positive attitude"],
    correctAnswer: 3
  },
  {
    id: 83,
    question: "When referring to defensive tactics, the acronym ABC stands for:",
    options: ["Arrest, beat, cuff", "Always be complacent", "Awareness, barrier, counter", "Anybody can"],
    correctAnswer: 2
  },
  {
    id: 84,
    question: "An aggressive individual applies a rear choke to an officer. The officer might utilize which technique to overcome the assault?",
    options: ["Foot stomp", "Groin strike", "Eye gouge", "Firearm", "It might be necessary to use any of the above methods to overcome such an attack"],
    correctAnswer: 4
  },
  {
    id: 85,
    question: "Panic may cause",
    options: ["Overreaction", "Rapid oxygen depletion/Hyperventilation", "Officer to \"freeze\"", "Any of the above"],
    correctAnswer: 3
  },
  {
    id: 86,
    question: "Handcuffs provide restraint to prevent attack, escape, or destruction of evidence.",
    options: ["Permanent", "Foolproof", "Temporary", "Stylish", "None of the above"],
    correctAnswer: 2
  },
  {
    id: 87,
    question: "The reason for handcuffing is to provide a greater degree of safety to the security officer, the prisoner, and the public.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 88,
    question: "Standing, kneeling, and prone are the three positions to apply handcuffs.",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 89,
    question: "When conducting a pat-frisk, the security officer is searching for",
    options: ["Priceless art", "Weapons", "Food", "Pets"],
    correctAnswer: 1
  },
  {
    id: 90,
    question: "Leaving a person unattended after being handcuffed is always a good practice.",
    options: ["True", "False"],
    correctAnswer: 1
  },
  {
    id: 91,
    question: "The minimum qualifying percentage that must be achieved in order to qualify when shooting a pistol is",
    options: ["50%", "65%", "90%", "70%"],
    correctAnswer: 3
  },
  {
    id: 92,
    question: "Leaving a firearm unsecured is generally acceptable if the security officer is in his or her own home.",
    options: ["True", "False"],
    correctAnswer: 1
  },
  {
    id: 93,
    question: "Texas Penal Code Section 46.15 provides non-applicability allowing on-duty commissioned security officers to carry a club (baton).",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 94,
    question: "Only security officers that have received training provided by TCoLE may be allowed to carry a chemical dispensing device:",
    options: ["True", "False"],
    correctAnswer: 0
  },
  {
    id: 95,
    question: "The head and throat are the primary targets of baton strikes.",
    options: ["The head and throat", "The groin and spine", "Attacking limbs", "A and B are correct", "None of the above"],
    correctAnswer: 4
  },
  {
    id: 96,
    question: "Infra Orbital, Common Peroneal, and Tibial Nerve are motor nerve points targeted by a baton.",
    options: ["Infra Orbital", "Common Peroneal", "Hypoglossal", "Tibial Nerve", "B and D are correct"],
    correctAnswer: 4
  },
  {
    id: 97,
    question: "The Circle-Slash method is the most common method to respond to someone grabbing the security officer's baton during a struggle.",
    options: ["Surrender", "Circle-Slash", "Brute strength", "Heimlich maneuver"],
    correctAnswer: 1
  },
  {
    id: 98,
    question: "The passing grade for the Private Security Level 3 examination is:",
    options: ["100%", "90%", "75%", "50%"],
    correctAnswer: 2
  },
  {
    id: 99,
    question: "Generally, a security officer's report should contain a lot of opinion.",
    options: ["True", "False"],
    correctAnswer: 1
  },
  {
    id: 100,
    question: "Personal weapons available to the security officer include",
    options: ["Hands and feet", "Elbows and Knees", "Head and forearms", "Shins", "All of the above are personal weapons available to the security officer"],
    correctAnswer: 4
  }
];
